package vvitsp.model.bc.view;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 24 22:49:05 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StudentDetailsROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        StudentId {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getStudentId();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setStudentId((Number)value);
            }
        }
        ,
        RollNo {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getRollNo();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setRollNo((String)value);
            }
        }
        ,
        FirstName {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getFirstName();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setFirstName((String)value);
            }
        }
        ,
        LastName {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getLastName();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setLastName((String)value);
            }
        }
        ,
        Dob {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getDob();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setDob((Timestamp)value);
            }
        }
        ,
        Doj {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getDoj();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setDoj((Timestamp)value);
            }
        }
        ,
        Phone {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getPhone();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setPhone((String)value);
            }
        }
        ,
        Mobile {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getMobile();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setMobile((String)value);
            }
        }
        ,
        Gender {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getGender();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setGender((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        ObjectVersionId {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getObjectVersionId();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setObjectVersionId((Number)value);
            }
        }
        ,
        Active {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getActive();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setActive((Number)value);
            }
        }
        ,
        Address {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getAddress();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setAddress((String)value);
            }
        }
        ,
        UserId {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getUserId();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setUserId((Number)value);
            }
        }
        ,
        Email {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getEmail();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setEmail((String)value);
            }
        }
        ,
        Password {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getPassword();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setPassword((String)value);
            }
        }
        ,
        UserType {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getUserType();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setUserType((Number)value);
            }
        }
        ,
        StudentId1 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getStudentId1();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setStudentId1((Number)value);
            }
        }
        ,
        StaffId {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getStaffId();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setStaffId((Number)value);
            }
        }
        ,
        ParentId {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getParentId();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setParentId((Number)value);
            }
        }
        ,
        CreatedBy1 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getCreatedBy1();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setCreatedBy1((String)value);
            }
        }
        ,
        CreationDate1 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getCreationDate1();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setCreationDate1((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy1 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getLastUpdatedBy1();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setLastUpdatedBy1((String)value);
            }
        }
        ,
        LastUpdateDate1 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getLastUpdateDate1();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setLastUpdateDate1((Timestamp)value);
            }
        }
        ,
        ObjectVersionId1 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getObjectVersionId1();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setObjectVersionId1((Number)value);
            }
        }
        ,
        Active1 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getActive1();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setActive1((Number)value);
            }
        }
        ,
        RelStudentBranchSectionId {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getRelStudentBranchSectionId();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setRelStudentBranchSectionId((Number)value);
            }
        }
        ,
        StudentId2 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getStudentId2();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setStudentId2((Number)value);
            }
        }
        ,
        BranchId {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getBranchId();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setBranchId((Number)value);
            }
        }
        ,
        SectionId {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getSectionId();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setSectionId((Number)value);
            }
        }
        ,
        IsMonitor {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getIsMonitor();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setIsMonitor((Number)value);
            }
        }
        ,
        AcedemicStartYear {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getAcedemicStartYear();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setAcedemicStartYear((Number)value);
            }
        }
        ,
        AcedemicEndYear {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getAcedemicEndYear();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setAcedemicEndYear((Number)value);
            }
        }
        ,
        CreatedBy2 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getCreatedBy2();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setCreatedBy2((String)value);
            }
        }
        ,
        CreationDate2 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getCreationDate2();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setCreationDate2((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy2 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getLastUpdatedBy2();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setLastUpdatedBy2((String)value);
            }
        }
        ,
        LastUpdateDate2 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getLastUpdateDate2();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setLastUpdateDate2((Timestamp)value);
            }
        }
        ,
        ObjectVersionId2 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getObjectVersionId2();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setObjectVersionId2((Number)value);
            }
        }
        ,
        Active2 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getActive2();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setActive2((Number)value);
            }
        }
        ,
        SemesterId {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getSemesterId();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setSemesterId((Number)value);
            }
        }
        ,
        UpdateRequest {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getUpdateRequest();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setUpdateRequest((Boolean)value);
            }
        }
        ,
        BranchVO1 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getBranchVO1();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SectionVO1 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getSectionVO1();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SemesterVO1 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getSemesterVO1();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StudentHistoryVO1 {
            public Object get(StudentDetailsROVORowImpl obj) {
                return obj.getStudentHistoryVO1();
            }

            public void put(StudentDetailsROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(StudentDetailsROVORowImpl object);

        public abstract void put(StudentDetailsROVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int STUDENTID = AttributesEnum.StudentId.index();
    public static final int ROLLNO = AttributesEnum.RollNo.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int DOB = AttributesEnum.Dob.index();
    public static final int DOJ = AttributesEnum.Doj.index();
    public static final int PHONE = AttributesEnum.Phone.index();
    public static final int MOBILE = AttributesEnum.Mobile.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int PASSWORD = AttributesEnum.Password.index();
    public static final int USERTYPE = AttributesEnum.UserType.index();
    public static final int STUDENTID1 = AttributesEnum.StudentId1.index();
    public static final int STAFFID = AttributesEnum.StaffId.index();
    public static final int PARENTID = AttributesEnum.ParentId.index();
    public static final int CREATEDBY1 = AttributesEnum.CreatedBy1.index();
    public static final int CREATIONDATE1 = AttributesEnum.CreationDate1.index();
    public static final int LASTUPDATEDBY1 = AttributesEnum.LastUpdatedBy1.index();
    public static final int LASTUPDATEDATE1 = AttributesEnum.LastUpdateDate1.index();
    public static final int OBJECTVERSIONID1 = AttributesEnum.ObjectVersionId1.index();
    public static final int ACTIVE1 = AttributesEnum.Active1.index();
    public static final int RELSTUDENTBRANCHSECTIONID = AttributesEnum.RelStudentBranchSectionId.index();
    public static final int STUDENTID2 = AttributesEnum.StudentId2.index();
    public static final int BRANCHID = AttributesEnum.BranchId.index();
    public static final int SECTIONID = AttributesEnum.SectionId.index();
    public static final int ISMONITOR = AttributesEnum.IsMonitor.index();
    public static final int ACEDEMICSTARTYEAR = AttributesEnum.AcedemicStartYear.index();
    public static final int ACEDEMICENDYEAR = AttributesEnum.AcedemicEndYear.index();
    public static final int CREATEDBY2 = AttributesEnum.CreatedBy2.index();
    public static final int CREATIONDATE2 = AttributesEnum.CreationDate2.index();
    public static final int LASTUPDATEDBY2 = AttributesEnum.LastUpdatedBy2.index();
    public static final int LASTUPDATEDATE2 = AttributesEnum.LastUpdateDate2.index();
    public static final int OBJECTVERSIONID2 = AttributesEnum.ObjectVersionId2.index();
    public static final int ACTIVE2 = AttributesEnum.Active2.index();
    public static final int SEMESTERID = AttributesEnum.SemesterId.index();
    public static final int UPDATEREQUEST = AttributesEnum.UpdateRequest.index();
    public static final int BRANCHVO1 = AttributesEnum.BranchVO1.index();
    public static final int SECTIONVO1 = AttributesEnum.SectionVO1.index();
    public static final int SEMESTERVO1 = AttributesEnum.SemesterVO1.index();
    public static final int STUDENTHISTORYVO1 = AttributesEnum.StudentHistoryVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public StudentDetailsROVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute StudentId.
     * @return the StudentId
     */
    public Number getStudentId() {
        return (Number) getAttributeInternal(STUDENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StudentId.
     * @param value value to set the  StudentId
     */
    public void setStudentId(Number value) {
        setAttributeInternal(STUDENTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RollNo.
     * @return the RollNo
     */
    public String getRollNo() {
        return (String) getAttributeInternal(ROLLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RollNo.
     * @param value value to set the  RollNo
     */
    public void setRollNo(String value) {
        setAttributeInternal(ROLLNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FirstName.
     * @return the FirstName
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FirstName.
     * @param value value to set the  FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastName.
     * @return the LastName
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastName.
     * @param value value to set the  LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Dob.
     * @return the Dob
     */
    public Timestamp getDob() {
        return (Timestamp) getAttributeInternal(DOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Dob.
     * @param value value to set the  Dob
     */
    public void setDob(Timestamp value) {
        setAttributeInternal(DOB, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Doj.
     * @return the Doj
     */
    public Timestamp getDoj() {
        return (Timestamp) getAttributeInternal(DOJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Doj.
     * @param value value to set the  Doj
     */
    public void setDoj(Timestamp value) {
        setAttributeInternal(DOJ, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Phone.
     * @return the Phone
     */
    public String getPhone() {
        return (String) getAttributeInternal(PHONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Phone.
     * @param value value to set the  Phone
     */
    public void setPhone(String value) {
        setAttributeInternal(PHONE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Mobile.
     * @return the Mobile
     */
    public String getMobile() {
        return (String) getAttributeInternal(MOBILE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Mobile.
     * @param value value to set the  Mobile
     */
    public void setMobile(String value) {
        setAttributeInternal(MOBILE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Gender.
     * @return the Gender
     */
    public Number getGender() {
        return (Number) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Gender.
     * @param value value to set the  Gender
     */
    public void setGender(Number value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy.
     * @param value value to set the  CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreationDate.
     * @return the CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate.
     * @param value value to set the  CreationDate
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy.
     * @param value value to set the  LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate.
     * @param value value to set the  LastUpdateDate
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectVersionId.
     * @return the ObjectVersionId
     */
    public Number getObjectVersionId() {
        return (Number) getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ObjectVersionId.
     * @param value value to set the  ObjectVersionId
     */
    public void setObjectVersionId(Number value) {
        setAttributeInternal(OBJECTVERSIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Active.
     * @return the Active
     */
    public Number getActive() {
        return (Number) getAttributeInternal(ACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Active.
     * @param value value to set the  Active
     */
    public void setActive(Number value) {
        setAttributeInternal(ACTIVE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Address.
     * @return the Address
     */
    public String getAddress() {
        return (String) getAttributeInternal(ADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Address.
     * @param value value to set the  Address
     */
    public void setAddress(String value) {
        setAttributeInternal(ADDRESS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UserId.
     * @return the UserId
     */
    public Number getUserId() {
        return (Number) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UserId.
     * @param value value to set the  UserId
     */
    public void setUserId(Number value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Email.
     * @return the Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Email.
     * @param value value to set the  Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Password.
     * @return the Password
     */
    public String getPassword() {
        return (String) getAttributeInternal(PASSWORD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Password.
     * @param value value to set the  Password
     */
    public void setPassword(String value) {
        setAttributeInternal(PASSWORD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UserType.
     * @return the UserType
     */
    public Number getUserType() {
        return (Number) getAttributeInternal(USERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UserType.
     * @param value value to set the  UserType
     */
    public void setUserType(Number value) {
        setAttributeInternal(USERTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StudentId1.
     * @return the StudentId1
     */
    public Number getStudentId1() {
        return (Number) getAttributeInternal(STUDENTID1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StudentId1.
     * @param value value to set the  StudentId1
     */
    public void setStudentId1(Number value) {
        setAttributeInternal(STUDENTID1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StaffId.
     * @return the StaffId
     */
    public Number getStaffId() {
        return (Number) getAttributeInternal(STAFFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StaffId.
     * @param value value to set the  StaffId
     */
    public void setStaffId(Number value) {
        setAttributeInternal(STAFFID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ParentId.
     * @return the ParentId
     */
    public Number getParentId() {
        return (Number) getAttributeInternal(PARENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ParentId.
     * @param value value to set the  ParentId
     */
    public void setParentId(Number value) {
        setAttributeInternal(PARENTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy1.
     * @return the CreatedBy1
     */
    public String getCreatedBy1() {
        return (String) getAttributeInternal(CREATEDBY1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy1.
     * @param value value to set the  CreatedBy1
     */
    public void setCreatedBy1(String value) {
        setAttributeInternal(CREATEDBY1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreationDate1.
     * @return the CreationDate1
     */
    public Timestamp getCreationDate1() {
        return (Timestamp) getAttributeInternal(CREATIONDATE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate1.
     * @param value value to set the  CreationDate1
     */
    public void setCreationDate1(Timestamp value) {
        setAttributeInternal(CREATIONDATE1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedBy1.
     * @return the LastUpdatedBy1
     */
    public String getLastUpdatedBy1() {
        return (String) getAttributeInternal(LASTUPDATEDBY1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy1.
     * @param value value to set the  LastUpdatedBy1
     */
    public void setLastUpdatedBy1(String value) {
        setAttributeInternal(LASTUPDATEDBY1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdateDate1.
     * @return the LastUpdateDate1
     */
    public Timestamp getLastUpdateDate1() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate1.
     * @param value value to set the  LastUpdateDate1
     */
    public void setLastUpdateDate1(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectVersionId1.
     * @return the ObjectVersionId1
     */
    public Number getObjectVersionId1() {
        return (Number) getAttributeInternal(OBJECTVERSIONID1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ObjectVersionId1.
     * @param value value to set the  ObjectVersionId1
     */
    public void setObjectVersionId1(Number value) {
        setAttributeInternal(OBJECTVERSIONID1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Active1.
     * @return the Active1
     */
    public Number getActive1() {
        return (Number) getAttributeInternal(ACTIVE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Active1.
     * @param value value to set the  Active1
     */
    public void setActive1(Number value) {
        setAttributeInternal(ACTIVE1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RelStudentBranchSectionId.
     * @return the RelStudentBranchSectionId
     */
    public Number getRelStudentBranchSectionId() {
        return (Number) getAttributeInternal(RELSTUDENTBRANCHSECTIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RelStudentBranchSectionId.
     * @param value value to set the  RelStudentBranchSectionId
     */
    public void setRelStudentBranchSectionId(Number value) {
        setAttributeInternal(RELSTUDENTBRANCHSECTIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StudentId2.
     * @return the StudentId2
     */
    public Number getStudentId2() {
        return (Number) getAttributeInternal(STUDENTID2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StudentId2.
     * @param value value to set the  StudentId2
     */
    public void setStudentId2(Number value) {
        setAttributeInternal(STUDENTID2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BranchId.
     * @return the BranchId
     */
    public Number getBranchId() {
        return (Number) getAttributeInternal(BRANCHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BranchId.
     * @param value value to set the  BranchId
     */
    public void setBranchId(Number value) {
        setAttributeInternal(BRANCHID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SectionId.
     * @return the SectionId
     */
    public Number getSectionId() {
        return (Number) getAttributeInternal(SECTIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SectionId.
     * @param value value to set the  SectionId
     */
    public void setSectionId(Number value) {
        setAttributeInternal(SECTIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsMonitor.
     * @return the IsMonitor
     */
    public Number getIsMonitor() {
        return (Number) getAttributeInternal(ISMONITOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsMonitor.
     * @param value value to set the  IsMonitor
     */
    public void setIsMonitor(Number value) {
        setAttributeInternal(ISMONITOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AcedemicStartYear.
     * @return the AcedemicStartYear
     */
    public Number getAcedemicStartYear() {
        return (Number) getAttributeInternal(ACEDEMICSTARTYEAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AcedemicStartYear.
     * @param value value to set the  AcedemicStartYear
     */
    public void setAcedemicStartYear(Number value) {
        setAttributeInternal(ACEDEMICSTARTYEAR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AcedemicEndYear.
     * @return the AcedemicEndYear
     */
    public Number getAcedemicEndYear() {
        return (Number) getAttributeInternal(ACEDEMICENDYEAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AcedemicEndYear.
     * @param value value to set the  AcedemicEndYear
     */
    public void setAcedemicEndYear(Number value) {
        setAttributeInternal(ACEDEMICENDYEAR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy2.
     * @return the CreatedBy2
     */
    public String getCreatedBy2() {
        return (String) getAttributeInternal(CREATEDBY2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy2.
     * @param value value to set the  CreatedBy2
     */
    public void setCreatedBy2(String value) {
        setAttributeInternal(CREATEDBY2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreationDate2.
     * @return the CreationDate2
     */
    public Timestamp getCreationDate2() {
        return (Timestamp) getAttributeInternal(CREATIONDATE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate2.
     * @param value value to set the  CreationDate2
     */
    public void setCreationDate2(Timestamp value) {
        setAttributeInternal(CREATIONDATE2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedBy2.
     * @return the LastUpdatedBy2
     */
    public String getLastUpdatedBy2() {
        return (String) getAttributeInternal(LASTUPDATEDBY2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy2.
     * @param value value to set the  LastUpdatedBy2
     */
    public void setLastUpdatedBy2(String value) {
        setAttributeInternal(LASTUPDATEDBY2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdateDate2.
     * @return the LastUpdateDate2
     */
    public Timestamp getLastUpdateDate2() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate2.
     * @param value value to set the  LastUpdateDate2
     */
    public void setLastUpdateDate2(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectVersionId2.
     * @return the ObjectVersionId2
     */
    public Number getObjectVersionId2() {
        return (Number) getAttributeInternal(OBJECTVERSIONID2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ObjectVersionId2.
     * @param value value to set the  ObjectVersionId2
     */
    public void setObjectVersionId2(Number value) {
        setAttributeInternal(OBJECTVERSIONID2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Active2.
     * @return the Active2
     */
    public Number getActive2() {
        return (Number) getAttributeInternal(ACTIVE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Active2.
     * @param value value to set the  Active2
     */
    public void setActive2(Number value) {
        setAttributeInternal(ACTIVE2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SemesterId.
     * @return the SemesterId
     */
    public Number getSemesterId() {
        return (Number) getAttributeInternal(SEMESTERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SemesterId.
     * @param value value to set the  SemesterId
     */
    public void setSemesterId(Number value) {
        setAttributeInternal(SEMESTERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UpdateRequest.
     * @return the UpdateRequest
     */
    public Boolean getUpdateRequest() {
        if (this.getStudentId() == null) {
            return Boolean.FALSE;
        }

        RowSet historyVO1 = this.getStudentHistoryVO1();
        historyVO1.setNamedWhereClauseParam("bindStudentId", this.getStudentId());
        historyVO1.executeQuery();
        return historyVO1 != null && historyVO1.first() != null;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UpdateRequest.
     * @param value value to set the  UpdateRequest
     */
    public void setUpdateRequest(Boolean value) {
        setAttributeInternal(UPDATEREQUEST, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BranchVO1.
     */
    public RowSet getBranchVO1() {
        return (RowSet)getAttributeInternal(BRANCHVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SectionVO1.
     */
    public RowSet getSectionVO1() {
        return (RowSet)getAttributeInternal(SECTIONVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SemesterVO1.
     */
    public RowSet getSemesterVO1() {
        return (RowSet)getAttributeInternal(SEMESTERVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StudentHistoryVO1.
     */
    public RowSet getStudentHistoryVO1() {
        return (RowSet)getAttributeInternal(STUDENTHISTORYVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
