package vvitsp.model.bc.appModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 12 07:36:55 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommonAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CommonAMImpl() {
    }


    /**
     * Container's getter for LookupItemsROVO1.
     * @return LookupItemsROVO1
     */
    public ViewObjectImpl getLookupItemsROVO1() {
        return (ViewObjectImpl)findViewObject("LookupItemsROVO1");
    }

    /**
     * Container's getter for StudentVO3.
     * @return StudentVO3
     */
    public ViewObjectImpl getStudentVO1() {
        return (ViewObjectImpl)findViewObject("StudentVO1");
    }


    /**
     * Container's getter for StaffVO1.
     * @return StaffVO1
     */
    public ViewObjectImpl getStaffVO1() {
        return (ViewObjectImpl)findViewObject("StaffVO1");
    }

    /**
     * Container's getter for UserVO1.
     * @return UserVO1
     */
    public ViewObjectImpl getUserVO1() {
        return (ViewObjectImpl)findViewObject("UserVO1");
    }

    /**
     * Container's getter for StudentUserROVO1.
     * @return StudentUserROVO1
     */
    public ViewObjectImpl getStudentUserROVO1() {
        return (ViewObjectImpl)findViewObject("StudentUserROVO1");
    }

    /**
     * Container's getter for StaffUserROVO1.
     * @return StaffUserROVO1
     */
    public ViewObjectImpl getStaffUserROVO1() {
        return (ViewObjectImpl)findViewObject("StaffUserROVO1");
    }


    /**
     * Container's getter for NotificationROVO1.
     * @return NotificationROVO1
     */
    public ViewObjectImpl getNotificationROVO1() {
        return (ViewObjectImpl)findViewObject("NotificationROVO1");
    }

    /**
     * Container's getter for StudentHistoryVO1.
     * @return StudentHistoryVO1
     */
    public ViewObjectImpl getStudentHistoryVO1() {
        return (ViewObjectImpl)findViewObject("StudentHistoryVO1");
    }

    /**
     * Container's getter for QueryROVO1.
     * @return QueryROVO1
     */
    public ViewObjectImpl getQueryROVO1() {
        return (ViewObjectImpl)findViewObject("QueryROVO1");
    }

    /**
     * Container's getter for QueryVO1.
     * @return QueryVO1
     */
    public ViewObjectImpl getQueryVO1() {
        return (ViewObjectImpl)findViewObject("QueryVO1");
    }

    /**
     * Container's getter for StudentFirstYearAttendanceROVO1.
     * @return StudentFirstYearAttendanceROVO1
     */
    public ViewObjectImpl getStudentAttendanceROVO1() {
        return (ViewObjectImpl)findViewObject("StudentAttendanceROVO1");
    }

    /**
     * Container's getter for StudentDetailsROVO1.
     * @return StudentDetailsROVO1
     */
    public ViewObjectImpl getStudentDetailsROVO1() {
        return (ViewObjectImpl)findViewObject("StudentDetailsROVO1");
    }

    /**
     * Container's getter for BranchVO1.
     * @return BranchVO1
     */
    public ViewObjectImpl getBranchVO1() {
        return (ViewObjectImpl)findViewObject("BranchVO1");
    }

    /**
     * Container's getter for SectionVO1.
     * @return SectionVO1
     */
    public ViewObjectImpl getSectionVO1() {
        return (ViewObjectImpl)findViewObject("SectionVO1");
    }

    /**
     * Container's getter for SemesterVO1.
     * @return SemesterVO1
     */
    public ViewObjectImpl getSemesterVO1() {
        return (ViewObjectImpl)findViewObject("SemesterVO1");
    }

    /**
     * Container's getter for StudentBranchSectionVO1.
     * @return StudentBranchSectionVO1
     */
    public ViewObjectImpl getStudentBranchSectionVO1() {
        return (ViewObjectImpl)findViewObject("StudentBranchSectionVO1");
    }

    /**
     * Container's getter for AdminNotificationROVO1.
     * @return AdminNotificationROVO1
     */
    public ViewObjectImpl getAdminNotificationROVO1() {
        return (ViewObjectImpl)findViewObject("AdminNotificationROVO1");
    }

    /**
     * Container's getter for NotificationVO1.
     * @return NotificationVO1
     */
    public ViewObjectImpl getNotificationVO1() {
        return (ViewObjectImpl)findViewObject("NotificationVO1");
    }

    /**
     * Container's getter for QueryDetailsROVO1.
     * @return QueryDetailsROVO1
     */
    public ViewObjectImpl getQueryDetailsROVO1() {
        return (ViewObjectImpl)findViewObject("QueryDetailsROVO1");
    }

    /**
     * Container's getter for AdminSubjectROVO1.
     * @return AdminSubjectROVO1
     */
    public ViewObjectImpl getAdminSubjectROVO1() {
        return (ViewObjectImpl)findViewObject("AdminSubjectROVO1");
    }

    /**
     * Container's getter for SubjectVO1.
     * @return SubjectVO1
     */
    public ViewObjectImpl getSubjectVO1() {
        return (ViewObjectImpl)findViewObject("SubjectVO1");
    }

    /**
     * Container's getter for BranchSemesterSubjectVO1.
     * @return BranchSemesterSubjectVO1
     */
    public ViewObjectImpl getBranchSemesterSubjectVO1() {
        return (ViewObjectImpl)findViewObject("BranchSemesterSubjectVO1");
    }

    /**
     * Container's getter for StudentMarksROVO1.
     * @return StudentMarksROVO1
     */
    public ViewObjectImpl getStudentMarksROVO1() {
        return (ViewObjectImpl)findViewObject("StudentMarksROVO1");
    }
}
